"""initial migration

Revision ID: 58271ef7ea5e
Revises: 
Create Date: 2025-05-05 16:42:10.697378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58271ef7ea5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_users_email', table_name='users')
    # op.drop_constraint('users_email_key', 'users', type_='unique')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # # ### end Alembic commands ###
    pass

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_id'), table_name='users')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.create_unique_constraint('users_email_key', 'users', ['email'])
    # op.create_index('idx_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
    pass
